"""Regenerate docs/data.js from the canonical lexicons in cvgrader/data,
the sample resumes, and the job-description presets. Run after editing any:

    python scripts/make_presets.py      # only if presets changed
    python scripts/build_web_data.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "cvgrader" / "data"
SAMPLES = ROOT / "samples"
PRESETS = ROOT / "presets"
OUT = ROOT / "docs" / "data.js"

ACRONYMS = {"it": "IT", "ux": "UX", "ui": "UI", "qa": "QA", "hr": "HR", "seo": "SEO",
            "ml": "ML", "ai": "AI", "devops": "DevOps", "sdr": "SDR", "rep": "Rep"}


def pretty(slug: str) -> str:
    return " ".join(ACRONYMS.get(w, w.capitalize()) for w in slug.split("-"))


def main():
    payload = {
        "skills": json.loads((DATA / "skills.json").read_text(encoding="utf-8")),
        "verbs": json.loads((DATA / "verbs.json").read_text(encoding="utf-8")),
        "buzzwords": json.loads((DATA / "buzzwords.json").read_text(encoding="utf-8")),
    }
    resumes = {f.stem: f.read_text(encoding="utf-8")
               for f in sorted(SAMPLES.glob("*resume*.txt"))}

    presets: dict = {}
    for f in sorted(PRESETS.glob("*--*.txt")):
        category, slug = f.stem.split("--", 1)
        presets.setdefault(category, []).append(
            {"id": f.stem, "label": pretty(slug), "text": f.read_text(encoding="utf-8")})
    for items in presets.values():
        items.sort(key=lambda x: x["label"])

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        "// GENERATED by scripts/build_web_data.py - do not edit by hand.\n"
        "// Sources: cvgrader/data/*.json, samples/*resume*.txt, presets/*.txt\n"
        f"const CVG_DATA = {json.dumps(payload)};\n"
        f"const CVG_SAMPLES = {json.dumps({'resumes': resumes})};\n"
        f"const CVG_PRESETS = {json.dumps(presets)};\n"
        "if (typeof module !== 'undefined') module.exports = { CVG_DATA, CVG_SAMPLES, CVG_PRESETS };\n",
        encoding="utf-8")
    n = sum(len(v) for v in presets.values())
    print(f"wrote {OUT} ({n} presets in {len(presets)} categories)")


if __name__ == "__main__":
    main()
