"""Regenerate docs/data.js from the canonical lexicons in cvgrader/data,
the sample resumes, and the job-description presets. Run after editing any:

    python scripts/make_presets.py      # only if presets changed
    python scripts/build_web_data.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "cvgrader" / "data"
SAMPLES = ROOT / "samples"
PRESETS = ROOT / "presets"
OUT = ROOT / "docs" / "data.js"

ACRONYMS = {"it": "IT", "ux": "UX", "ui": "UI", "qa": "QA", "hr": "HR", "seo": "SEO",
            "ml": "ML", "ai": "AI", "devops": "DevOps", "sdr": "SDR", "rep": "Rep"}


def pretty(slug: str) -> str:
    return " ".join(ACRONYMS.get(w, w.capitalize()) for w in slug.split("-"))


def main():
    payload = {
        "skills": json.loads((DATA / "skills.json").read_text(encoding="utf-8")),
        "verbs": json.loads((DATA / "verbs.json").read_text(encoding="utf-8")),
        "buzzwords": json.loads((DATA / "buzzwords.json").read_text(encoding="utf-8")),
    }
    resumes = {f.stem: f.read_text(encoding="utf-8")
               for f in sorted(SAMPLES.glob("*resume*.txt"))}

    # <cat>--<slug>.txt is a single posting; <cat>--<slug>--<level>.txt variants
    # are grouped under one picker entry with a "levels" dict.
    LEVELS = ["intern", "junior", "mid", "senior"]
    roles: dict = {}
    n_files = 0
    for f in sorted(PRESETS.glob("*--*.txt")):
        n_files += 1
        parts = f.stem.split("--")
        cat, slug = parts[0], parts[1]
        level = parts[2] if len(parts) > 2 else None
        item = roles.setdefault((cat, slug), {"id": f"{cat}--{slug}", "label": pretty(slug)})
        text = f.read_text(encoding="utf-8")
        if level:
            item.setdefault("levels", {})[level] = text
        else:
            item["text"] = text
    presets: dict = {}
    for (cat, _slug), item in roles.items():
        if "levels" in item:
            item["levels"] = {lv: item["levels"][lv] for lv in LEVELS if lv in item["levels"]}
        presets.setdefault(cat, []).append(item)
    for items in presets.values():
        items.sort(key=lambda x: x["label"])

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        "// GENERATED by scripts/build_web_data.py - do not edit by hand.\n"
        "// Sources: cvgrader/data/*.json, samples/*resume*.txt, presets/*.txt\n"
        f"const CVG_DATA = {json.dumps(payload)};\n"
        f"const CVG_SAMPLES = {json.dumps({'resumes': resumes})};\n"
        f"const CVG_PRESETS = {json.dumps(presets)};\n"
        "if (typeof module !== 'undefined') module.exports = { CVG_DATA, CVG_SAMPLES, CVG_PRESETS };\n",
        encoding="utf-8")
    n = sum(len(v) for v in presets.values())
    print(f"wrote {OUT} ({n_files} posting files -> {n} picker entries "
          f"in {len(presets)} categories)")


if __name__ == "__main__":
    main()
