"""Regenerate docs/data.js from the canonical lexicons in cvgrader/data
and the sample files. Run after editing any of those:

    python scripts/build_web_data.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "cvgrader" / "data"
SAMPLES = ROOT / "samples"
OUT = ROOT / "docs" / "data.js"


def main():
    payload = {
        "skills": json.loads((DATA / "skills.json").read_text(encoding="utf-8")),
        "verbs": json.loads((DATA / "verbs.json").read_text(encoding="utf-8")),
        "buzzwords": json.loads((DATA / "buzzwords.json").read_text(encoding="utf-8")),
    }
    samples = {"resumes": {}, "jds": {}}
    for f in sorted(SAMPLES.glob("*.txt")):
        text = f.read_text(encoding="utf-8")
        if "resume" in f.stem:
            samples["resumes"][f.stem] = text
        else:
            samples["jds"][f.stem] = text

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        "// GENERATED by scripts/build_web_data.py - do not edit by hand.\n"
        "// Canonical source: cvgrader/data/*.json and samples/*.txt\n"
        f"const CVG_DATA = {json.dumps(payload)};\n"
        f"const CVG_SAMPLES = {json.dumps(samples)};\n"
        "if (typeof module !== 'undefined') module.exports = { CVG_DATA, CVG_SAMPLES };\n",
        encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
